name: Build Windows Executable

on:
  push:
    branches: [ "main", "master" ] # Τρέχει κάθε φορά που κάνεις push

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # <-- ΕΝΗΜΕΡΩΘΗΚΕ ΣΕ v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Executable (.exe)
        # Βεβαιώσου ότι το παρακάτω path προς το JAR είναι το σωστό
        run: native-image -jar Release/GlwssaPlusPlus.jar glwssa --no-fallback --initialize-at-build-time=org.antlr.v4.runtime

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4 # <-- ΕΝΗΜΕΡΩΘΗΚΕ ΣΕ v4
        with:
          name: Glwssa-Compiler-Windows
          path: glwssa.exe
